### PR TITLE
refactor(contract): split lib.rs into domain modules

### LINKED ISSUE #1403: Refactor: Split lib.rs into domain modules
Split the monolithic `lib.rs` (230k+ bytes) into focused domain modules: `pool.rs`, `prediction.rs`, `admin.rs`, `oracle.rs`, `referral.rs`, and `treasury.rs`. Maintain the same public API surface while improving code organization and maintainability.

### PR DESCRIPTION
**Pull request by Divine-designs**
# Description

Splits the monolithic `contract/contracts/predifi-contract/src/lib.rs` into six focused domain modules, as requested in the issue. Follows the module conventions already established in the crate (`constants.rs`, `events.rs`, `payouts.rs`, `safe_math.rs`, ...).

**This is a pure code move — there is no behaviour change.** No function body, signature, storage key, event or error was modified. Nothing was renamed, and no unrelated code was reformatted.

Closes #1403

## Before / after

| File | Lines | Size | Contract entrypoints |
|---|---|---|---|
| `lib.rs` **before** | 6,673 | 260 KB | 81 |
| `lib.rs` **after** | 2,030 | 84 KB | 0 |
| `admin.rs` | 1,239 | 44 KB | 37 |
| `pool.rs` | 1,584 | 64 KB | 20 |
| `prediction.rs` | 930 | 40 KB | 5 |
| `oracle.rs` | 667 | 22 KB | 8 + `OracleCallback` impl |
| `referral.rs` | 171 | 6 KB | 7 |
| `treasury.rs` | 144 | 5 KB | 3 |

`lib.rs` shrinks by 69%. Total line count grows by 92 lines, entirely from the seven new module headers and their `use` blocks.

## Structure chosen: split `#[contractimpl]` blocks

Each domain module carries its own `#[contractimpl] impl PredifiContract { ... }` block. There are **no delegating wrappers** — the entrypoints themselves moved.

This works because `lib.rs` already contained four separate `#[contractimpl] impl PredifiContract` blocks before this PR, so the SDK plainly supports it; the only new thing is that they now live in different modules. I verified this compiles with a single-function slice before moving the other 6,600 lines.

`lib.rs` retains:
- the `#[contract] pub struct PredifiContract`
- all shared types (`Pool`, `DataKey`, `PredifiError`, `Config`, ...), constants and event structs
- the `OracleCallback` trait declaration
- the **33 cross-domain private helpers** (`require_not_paused`, `require_admin_role`, `extend_persistent`, `get_config`, `validate_pool_invariants`, `calculate_dynamic_fee`, ...)

The private helpers stay in `lib.rs` deliberately. They live in the crate-root `impl` block, so they remain visible to every submodule with **no visibility widening** — nothing had to be promoted to `pub(crate)`, which keeps them out of the exported contract surface exactly as before.

Domain-private helpers used by only one domain moved with it: `claim_winnings_internal` → `prediction.rs`, and the nine `price_*` / `load_price_*` resolution helpers → `oracle.rs`.

### The only non-move edits

1. The `use` statements each new module needs. These include `PredifiContractArgs` and `PredifiContractClient` — `#[contractimpl]` requires both in scope when it expands outside the module hosting `#[contract]`.
2. `use crate::gas_opt;` in `pool.rs`, because two `gas_opt::` calls were previously resolving against the crate root.
3. Dropped `log` from the `soroban_sdk` import in `lib.rs` and `token` from `admin.rs`, as they became unused where they were.
4. `mod` declarations in `lib.rs` are now sorted (rustfmt did this while adding the six new ones).

## How Has This Been Tested?

> [!IMPORTANT]
> **`main` does not currently compile.** The verification below works around that; please read this section rather than just looking at CI.

### Pre-existing breakage on `main` (NOT introduced here, NOT fixed here)

`cargo build` fails on `upstream/main` with two errors:

1. `error: contract function name is too long: 34, max is 32` — `batch_remove_tokens_from_whitelist`. Fixing this means renaming an exported contract function, which is a real API change and a product decision, so I left it alone. It now reports at `admin.rs:578`.
2. `error[E0594]: cannot assign to pool.description, as pool is not declared as mutable` in `update_pool_description`. A duplicated re-read shadows the earlier `let mut pool` with a non-mut binding, so the later assignment can't compile. Looks like a bad merge. It now reports at `pool.rs:665`.

The test build has 24 further errors in `edge_case_tests.rs` (15), `boundary_edge_case_tests.rs` (7) and `storage_test.rs` (2) — tests calling contract methods that don't exist (`get_pool_id_counter`, `is_token_whitelisted`, `is_paused`) and `.unwrap()` on a non-`Result` `create_pool`.

`cargo fmt --all -- --check` also already fails on `main` with 44 diffs across 10 files. I did **not** fix those, to keep this diff a pure move.

I have deliberately preserved all of the above byte-for-byte.

### How I verified anyway

Since a broken baseline can't prove anything, I applied a **temporary local patch** (never committed) that makes the crate build: shorten the over-long function name, add the missing `mut`, and `#[cfg(any())]` out the three broken test modules. I then ran the full suite against that patch on **both** `upstream/main` and this branch.

| Check | `upstream/main` + temp patch | This branch + temp patch |
|---|---|---|
| `cargo build` | clean, 2 warnings | clean, **same** 2 warnings |
| `cargo test` (workspace) | 39 passed | 39 passed |
| `cargo test` (predifi-contract) | 426 tests — **421 passed, 5 failed** | 426 tests — **421 passed, 5 failed** |
| Failing test set | see below | **identical, same 5** |
| `cargo clippy --all-targets -- -D warnings` | 28 lints | **identical tally, no new lints** |
| `cargo build --target wasm32-unknown-unknown --release` | builds | builds |

The 5 pre-existing failures, unchanged before and after:

```
boundary_tests::batch_claim_invalid_pool_ids_yield_zero_not_failure
boundary_tests::batch_claim_large_batch_is_accepted
boundary_tests::batch_claim_mixed_valid_and_invalid_ids_returns_an_entry_for_each
boundary_tests::set_stake_limits_accepts_i128_max_ceiling
test::test_resolve_pool_from_price_applies_tolerance_bounded_match
```

**No test file was edited.** `test.rs` and every other test module are untouched in this diff.

### Proof the public API is identical

The strongest check: I built the release WASM from both trees and dumped the contract spec with `stellar contract info interface`.

- **81 exported contract functions before, 81 after**
- **Identical signature set** — no additions, removals or changes
- Every line of the interface dump matches; only the emission order differs, because functions are now grouped per module

I also diffed all 124 functions between the old `lib.rs` and the new module set after normalising whitespace and comments: **124 before, 124 after, none missing, none extra, zero body differences.**

## Type of Change

- [x] CI/CD or internal tool improvement (refactor — no functional change)

## Screenshots / Recordings

N/A — no frontend/UI changes.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas (all existing doc comments moved with their functions; each new module has a header doc comment)
- [ ] I have made corresponding changes to the documentation — not applicable, no behaviour changed
- [x] My changes generate no new warnings (warning set is byte-identical to baseline)
- [ ] I have added tests — not applicable, this is a pure code move; existing tests are the regression check and are unmodified
- [x] New and existing unit tests pass locally with my changes (identical results to baseline; see above)
- [x] Any dependent changes have been merged and published in downstream modules

## Notes for the reviewer

- Reviewing by function body is unnecessary — the WASM interface comparison and the 124-function body diff above cover it. The useful review question is whether the **domain boundaries** are the ones you want.
- Two judgement calls worth a look: `set_treasury` went to `treasury.rs` (not `admin.rs`) since it configures the treasury; and the whitelist functions went to `admin.rs` since they are admin-gated protocol configuration.
- The two compile errors and the 24 test-build errors on `main` are worth separate issues if none exist yet. Happy to open them.

### CODE REVIEW

**Review by Yunusabdul38 — APPROVED** [review]
LGTM
